### ISSUE TITLE
The home page does not load after the first login

### ISSUE THREAD

**Issue by lebao3105** [FluentHub/FluentHub#314] opened 2022-10-01 15:17 UTC
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Dev

### 🔢 What version/architecture of FluentHub are you on?

Version: 0.3.8.0 | MS Store release | Windows x64

### 📄 Description

This is the first time I use FluentHub. After logged in the GitHub account, the home page wasn't loaded, threw an error: Object reference not set to an instance of an object. Also the notifications page too.

### 🤔 Expected behavior

The app starts normally.

### 📟 Stack Trace

<details><summary>Stack trace details</summary><div>

```
   at FluentHub.Octokit.Queries.Users.NotificationQueries.<GetAllAsync>d__0.MoveNext() + 0x8ed
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadHomeContentsAsync>d__25.MoveNext() + 0x371
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadUserHomePageAsync>d__24.MoveNext() + 0x1e0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at Microsoft.Toolkit.Mvvm.ComponentModel.ObservableObject.<>c__DisplayClass20_0`1.<<SetPropertyAndNotifyOnCompletion>g__MonitorTask|0>d.MoveNext() + 0xab
```

</div></details>

### 📸 Assets

```
2022-10-01 21:25:11.961 +07:00 [ERR] LoadHomeContentsAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentHub.Octokit.Queries.Users.NotificationQueries.<GetAllAsync>d__0.MoveNext() + 0x8b8
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadHomeContentsAsync>d__25.MoveNext() + 0x36b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadUserHomePageAsync>d__24.MoveNext() + 0x110
```

**Comment by onein528** [comment] 2022-10-01 15:57
@lebao3105 This problem has existed for a long time, and it has been repeatedly corrected, but it has not been resolved yet. I can't reproduce it on my local machine, so I have no choice but to feel it. If you are the developer of UWP, is it possible to try debugging? If not, I added a new fix patch in the latest commit. I don't know if it works, but it will be released to the public in the next version bump. I would like you to test this problem again at that time.

**Comment by tomc128** [comment] 2022-10-03 21:02
If it helps, I also had this issue with the Microsoft Store version of the app. I've just built it from source and the home page now works. The profile page, however, shows `Invalid URI: The hostname could not be parsed` and the account settings page does not load at all.

**Comment by onein528** [comment] 2022-10-16 17:24
Can you check this issue on latest build v0.5? @lebao3105

**Comment by DeveloperWOW64** [comment] 2022-10-16 18:18
> The profile page, however, shows `Invalid URI: The hostname could not be parsed`

@tomc128 I've never seen this error before. It looks like this may be one of three errors:
* Internet error or Microsoft Policy (are you accessing this from a work or school Microsoft account, as in a Microsoft Azure Local/Active Directory environment (e.g., in my school, some school computers have GitHub servers blocked))
* Error within FluentHub requests (would've been fixed by now; obviously FluentHub on Microsoft Store is outdated)
* Error with your computer's permissions and firewall.

> and the account settings page does not load at all.

@tomc128 This is a known error. Currently, the FluentHub settings page is completely and absolutely broken and so far, there are no active plans to fix it.

Recently, FluentHub went through a major and completely https://github.com/FluentHub/FluentHub/labels/breaking%20change, meaning we couldn't really focus on anything else. Now with that out of the way, we can focus on more important yet minor changes to the codebase. So, please just bear with us as we fix it.

**Comment by lebao3105** [comment] 2022-10-28 13:02
> Can you check this issue on latest build v0.5? @lebao3105 https://github.com/FluentHub/FluentHub/releases/tag/0.5.0

Today I tried it, and the home page is working now. Thanks for your work!

**Closed** 2022-10-28 22:49 UTC
Labels: good first issue, bug
