### ISSUE TITLE
Bug: User profile page is very slow

### ISSUE THREAD

**Issue by J-Ciro** [FluentHub/FluentHub#395] opened 2023-05-21 21:47 UTC
### Before you start

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### What version of Windows is this issue present?

Windows 11

### What version/architecture of FluentHub are you on?

0.5.0.0 | X64 | RELEASE

### Description

When you visit your profile sectio, after your start scrolling down the page response its too slow

### Steps To Reproduce

1. Go to your profile
2. Start Scrolling

### Expected behavior

Slow scroll

### Stack Trace

<details><summary>Stack trace details</summary><div>

```
paste here
```

</div></details>

### 📸 Assets

![bug](https://github.com/FluentHub/FluentHub/assets/37349818/61d88be9-9715-4e79-9cf5-a7fbbee11dc6)

**Comment by 0x5bfa** [comment] 2023-05-21 23:11
Currently, Im working on redesigning the app. That issue is caused by loading contribution graph that has mass data. Probably I will remove in the future update.

**Comment by 0x5bfa** [comment] 2023-07-31 04:27
Thank you for feedback.

This was fixed in v0.5.1

**Closed by 0x5bfa** 2023-07-31 04:27 UTC
Labels: bug
