### ISSUE TITLE
Navigation does not work

### ISSUE THREAD

**Issue by KK-Designs** [FluentHub/FluentHub#263] opened 2022-09-14 04:55 UTC
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11

### 🔢 What version/architecture of FluentHub are you on?

None of the navigation systems works; I click on a button, for example, Notifications, and nothing happens. Same with any other button. Comment buttons and some functionality is grayed out. How do I fix this? Thank you.

### 📄 Description

None of the navigation systems works; I click on a button, for example, Notifications, and nothing happens. Same with any other button. Comment buttons and some functionality is grayed out. How do I fix this? Thank you.

### 🪜 Steps To Reproduce

Click any button that changes the page

### 🤔 Expected behavior

Go to said page and display the data 

### 📸 Assets

[New-Issue-·-FluentHub-FluentHub.webm](https://user-images.githubusercontent.com/71038229/190062849-1a66c661-e8cb-419e-97e9-30e60e212634.webm)

**Comment by DeveloperWOW64** [comment] 2022-09-14 07:09
Duplicate of #256

**Closed** 2022-09-14 07:09 UTC
Labels: bug

**Comment by onein528** [comment] 2022-09-14 10:25
@KK-Designs hi. This app is under construction. Some of function is doesn't work and not implemented.

**Comment by KK-Designs** [comment] 2022-09-15 00:49
> @KK-Designs hi. This app is under construction. Some of function is doesn't work and not implemented.

Wondering why this issue was closed "this as not panned" but I see hopefully it get fixed up.

**Comment by onein528** [comment] 2022-09-15 05:22
This is not originally navigation issue.
