### ISSUE TITLE
Home Page does not work

### ISSUE THREAD

**Issue by senolfndk** [FluentHub/FluentHub#315] opened 2022-10-03 13:55 UTC
### ⏱️ Before you start...

- [X] Have you updated FluentHub? You might be using an old version.
- [X] Have you checked if a similar issue has already been reported?

### 🪟 What version of Windows is this issue present?

Windows 11 Beta

### 🔢 What version/architecture of FluentHub are you on?

0.3.8.0 | X64 | RELEASE

### 📄 Description

Home Page does not work

### 🤔 Expected behavior

Home Page functions in a regular manner

### 📟 Stack Trace

<details><summary>Stack trace details</summary><div>

```
2022-10-03 16:48:13.288 +03:00 [ERR] LoadHomeContentsAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentHub.Octokit.Queries.Users.NotificationQueries.<GetAllAsync>d__0.MoveNext() + 0x8b8
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadHomeContentsAsync>d__25.MoveNext() + 0x36b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadUserHomePageAsync>d__24.MoveNext() + 0x110

2022-10-03 16:48:23.942 +03:00 [ERR] LoadHomeContentsAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentHub.Octokit.Queries.Users.NotificationQueries.<GetAllAsync>d__0.MoveNext() + 0x8b8
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadHomeContentsAsync>d__25.MoveNext() + 0x36b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadUserHomePageAsync>d__24.MoveNext() + 0x110

2022-10-03 16:49:28.010 +03:00 [ERR] LoadHomeContentsAsync
System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentHub.Octokit.Queries.Users.NotificationQueries.<GetAllAsync>d__0.MoveNext() + 0x8b8
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadHomeContentsAsync>d__25.MoveNext() + 0x36b
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0x70
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x38
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task) + 0x17
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult() + 0xb
   at FluentHub.Uwp.ViewModels.Home.UserHomeViewModel.<LoadUserHomePageAsync>d__24.MoveNext() + 0x110
```

</div></details>

### 📸 Assets

![Ekran görüntüsü 2022-10-03 164903](https://user-images.githubusercontent.com/52818836/193595134-298bc339-8a8c-4c17-b9e1-0ba4bc433285.png)

**Comment by DeveloperWOW64** [comment] 2022-10-03 16:03
Hi @senolfndk. It looks like you've built from a Microsoft Store version. Is this correct?

**Comment by senolfndk** [comment] 2022-10-03 16:31
yes i downloaded it from the store

**Comment by DeveloperWOW64** [comment] 2022-10-03 16:55
Duplicate of #314

**Closed by DeveloperWOW64** 2022-10-03 16:55 UTC
Labels: bug, store only
